pipeline:
  identifier: Build_aroma23_reactcalculator_1732472188033
  name: Build reactcalculator
  orgIdentifier: default
  projectIdentifier: Demo
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: aroma23/reactcalculator
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: test
                  name: test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
          platform:
            arch: Arm64
            os: MacOS
          runtime:
            spec: {}
            type: Docker
        type: CI
